# Generated by Django 5.1.3 on 2024-11-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_city_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='pin_code',
            new_name='pin',
        ),
    ]
