# Generated by Django 5.1.3 on 2024-11-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_paid_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
